[build]
  command = "webpack --mode=production && cp -R /Users/heidimorsky/Desktop/MyPortfolio/converter_PHP/json_converter_UI/templates/* public/"
  publish = "public/"

[[redirects]]
  from = "/*"
  to = "/templates/base.html.twig"
  status = 200

[[headers]]
  for = "/*"
    [headers.values]
      X-Frame-Options = "DENY"
      X-XSS-Protection = "1; mode=block"
      X-Content-Type-Options = "nosniff"

[[headers]]
  for = "/*.php"
    [headers.values]
      Cache-Control = "public, max-age=3600"

[[headers]]
  for = "/templates/base.html.twig"
    [headers.values]
      Cache-Control = "public, max-age=3600"
